### ISSUE TITLE
Plan Hash Instability in recursive union query

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#3139]
After publishing 4.1.4.0, some of the recursive CTE queries began to fail when run in multi-server configuration mode. Namely:

```yaml
    -
      - query: with recursive c1 as (
            select id, parent from t1 where parent = -1
            union all
            select b.id, b.parent from c1 as a, t1 as b where a.id = b.parent) select id from c1
      - supported_version: 4.1.4.0
      - explain: RUNION q0, q1 { INITIAL { ISCAN(PARENTIDX [EQUALS promote(@c15 AS LONG)]) | INSERT INTO TEMP q1 } RECURSIVE  { ISCAN(CHILDIDX <,>) | FLATMAP q2 -> { TEMP SCAN base() | FILTER _.ID EQUALS q2.PARENT AS q3 RETURN (q2.ID AS ID, q2.PARENT AS PARENT) } | INSERT INTO TEMP q1 }} | MAP (_.ID AS ID)
      - maxRows: 1
```

Which would fail when running the second continuation with a query plan hash mismatch failure:

```
com.apple.foundationdb.relational.api.exceptions.ContextualSQLException: cannot continue query due to mismatch between serialized and actual plan hash
```

Looking into this more, it seems like the root cause is that the plan hash on this query plan isn't stable (some element of it is dependent on something JVM dependent, as it is stable across runs within the same JVM, but it changes every time we switch to a new process).

We didn't catch this before as the multi-version test configs are the only test configs we have that we continue across two different JVMs, and those queries were disabled prior to this most recent version being published.
